{% set version = "2.0.1" %}

package:
  name: svmtk
  version: {{ version }}

source:
  url: https://github.com/SVMTK/SVMTK/archive/v{{ version }}.tar.gz
  sha256: "7083c34aaff0efde8837715d89ebf84e9e2e2630756b52052667d8b3119ca293"
  patches:
    - 0001-Use-C-14.patch  # [osx]

build:
  skip: true  # [win]
  number: 1
  script_env:
    - CMAKE_DOWNLOAD_CGAL=OFF
    - CMAKE_DOWNLOAD_PYBIND11=OFF
    - CMAKE_BUILD_TESTING=OFF
  script: {{ PYTHON }} -m pip install -vv --ignore-installed --no-deps .

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]
  host:
    - libboost-devel
    - cgal-cpp >=6.0.0
    - setuptools
    - eigen
    - gmp
    - mpfr
    - pybind11
    - python
    - pip
  run:
    - gmp
    - mpfr
    - numpy
    - python

test:
  requires:
    - pytest
  imports:
    - SVMTK
  source_files:
    - tests
  commands:
    - pytest -v tests/Surface_test.py

about:
  home: https://github.com/SVMTK/SVMTK
  summary: Surface Volume Meshing Toolkit (SVMTK)
  description: |
    Surface Volume Meshing Toolkit (SVMTK) is a Python frontend
    for specific 2D and 3D mesh generation methods in the
    Computational Geometry Algorithms Library (CGAL).

    SVMTK was designed to create volume meshes of soft organic tissue surfaces,
    like the human brain, with the option to repair unphysical errors on the surfaces.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/SVMTK/SVMTK

extra:
  recipe-maintainers:
    - jorgensd
    - minrk
