build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
provider:
  linux_aarch64: default
test: native_and_emulated
